# Generated by Django 3.1.7 on 2021-03-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knotend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='images')),
                ('description', models.CharField(max_length=255)),
                ('datetime', models.DateField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
